"
I am an exception thrown when there is a timeout while waiting for the synchronization of a future.
"
Class {
	#name : 'TKTTimeoutException',
	#superclass : 'Error',
	#category : 'TaskIt-Futures',
	#package : 'TaskIt',
	#tag : 'Futures'
}
